#!/usr/bin/env bash

echo "Setting up"
sudo locale-gen en_GB.UTF-8
echo "- Updating"
sudo apt-get update -y
sudo apt-get upgrade -y
echo "- Installing: python-software-properties, software-properties-common, acl, htop, unzip, curl, git"
sudo apt-get install -y acl htop unzip curl git dos2unix

echo "Installing: NGINX"
sudo add-apt-repository ppa:nginx/stable -y
sudo apt-get update
sudo apt-get install -y nginx &> /dev/null
sudo rm /etc/nginx/sites-available/default
echo "- Copying nginx configuration"
sudo cp ~/saeris/site/server/common /etc/nginx/sites-available/common
sudo cp ~/saeris/site/server/default /etc/nginx/sites-available/default

echo "Installing: PHP + Composer"
sudo add-apt-repository ppa:ondrej/php -y
sudo apt-get update -y
sudo apt-get install -y php7.2-fpm php-apcu php7.2-dev php7.2-cli php7.2-tidy php7.2-json php7.2-fpm php7.2-intl php7.2-mysql php7.2-sqlite php7.2-curl php7.2-gd php7.2-mbstring php7.2-dom php7.2-xml php7.2-zip php7.2-tidy php7.2-bcmath
echo "- Updating PHP configuration"
sudo sed -i 's|display_errors = Off|display_errors = On|' /etc/php/7.2/fpm/php.ini
sudo sed -i 's|memory_limit = 128M|memory_limit = 1G|' /etc/php/7.2/fpm/php.ini
echo "- Installing composer"
sudo curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
sudo chmod +x /usr/local/bin/composer

echo "- Restarting services"
sudo service nginx restart
sudo service php7.2-fpm restart

echo "- Auto removing and cleaning up services"
sudo apt-get autoremove -y
sudo apt-get update -y
sudo apt-get upgrade -y

echo "FINISHED"
